#!/usr/bin/env bash
set -euo pipefail

#===============================================================================
# setup-ru-vps.sh — XRay VLESS+Reality на российском VPS
#
# Что делает:
#   Первый запуск:
#     1. Ставит XRay и wireguard-tools
#     2. Генерирует ключи (Reality через xray x25519, WG через wg genkey)
#     3. Поднимает СИСТЕМНЫЙ WireGuard с policy routing
#     4. Настраивает XRay: VLESS+Reality inbound, freedom outbound через wg0
#     5. Генерирует готовый конфиг sing-box для клиента
#     6. Выводит VLESS-ссылку и инструкцию
#
#   Повторный запуск:
#     Предлагает реконфигурацию (смена домена, UUID, ключей, WG)
#     без полной переустановки
#===============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

parse_x25519_private() { echo "$1" | grep -i "private" | awk '{print $NF}'; }
parse_x25519_public()  { echo "$1" | grep -iE "(public|password)" | awk '{print $NF}'; }

[[ $EUID -ne 0 ]] && err "Запустите от root: sudo $0"

# =====================================================================
# КОНСТАНТЫ И ПУТИ
# =====================================================================

XRAY_CONFIG="/usr/local/etc/xray/config.json"
CREDENTIALS_FILE="/root/vpn-credentials.txt"
PARAMS_FILE="/root/.vpn-params"
WG_DNS="1.1.1.1"

# =====================================================================
# ФУНКЦИИ: сохранение/загрузка параметров
# =====================================================================

save_params() {
    cat > "$PARAMS_FILE" << EOF
# VPN parameters — auto-generated by setup-ru-vps.sh
# Generated: $(date)
UUID=${UUID}
REALITY_PRIVATE_KEY=${REALITY_PRIVATE_KEY}
REALITY_PUBLIC_KEY=${REALITY_PUBLIC_KEY}
SHORT_ID=${SHORT_ID}
REALITY_DEST=${REALITY_DEST}
SERVER_IP=${SERVER_IP}
WG_CLIENT_IP=${WG_CLIENT_IP}
WG_PRIVATE=${WG_PRIVATE}
WG_PUBLIC=${WG_PUBLIC}
FOREIGN_IP=${FOREIGN_IP}
FOREIGN_PORT=${FOREIGN_PORT}
FOREIGN_WG_PUBKEY=${FOREIGN_WG_PUBKEY}
EOF
    chmod 600 "$PARAMS_FILE"
}

load_params() {
    if [[ -f "$PARAMS_FILE" ]]; then
        source "$PARAMS_FILE"
        return 0
    fi

    # -----------------------------------------------------------------
    # TEMPORARY MIGRATION: vpn-credentials.txt → .vpn-params
    # Для серверов, настроенных до введения .vpn-params.
    # TODO: Удалить этот блок в следующих версиях.
    # -----------------------------------------------------------------
    if [[ -f "$CREDENTIALS_FILE" ]]; then
        warn "Миграция: создаю $PARAMS_FILE из старого формата..."
        UUID=$(grep "^UUID:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        REALITY_PUBLIC_KEY=$(grep "^Reality Public Key:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        REALITY_PRIVATE_KEY=$(grep "^Reality Private Key:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        SHORT_ID=$(grep "^Short ID:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        REALITY_DEST=$(grep "^Маскировка:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        WG_CLIENT_IP=$(grep "^WG Client IP:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        WG_PRIVATE=$(grep "^WG Private Key:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        WG_PUBLIC=$(grep "^WG Public Key:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        local endpoint
        endpoint=$(grep "^Foreign Endpoint:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        FOREIGN_IP=$(echo "$endpoint" | cut -d: -f1)
        FOREIGN_PORT=$(echo "$endpoint" | cut -d: -f2)
        # FOREIGN_WG_PUBKEY не хранился в credentials — берём из wg0.conf
        FOREIGN_WG_PUBKEY=$(grep "^PublicKey" /etc/wireguard/wg0.conf 2>/dev/null | awk '{print $NF}' || true)
        SERVER_IP=$(grep "^Server IP:" "$CREDENTIALS_FILE" | awk '{print $NF}' || true)
        [[ -z "$SERVER_IP" ]] && SERVER_IP=$(curl -s4 ifconfig.me || echo "UNKNOWN")
        save_params
        log "Миграция завершена: $PARAMS_FILE создан"
        return 0
    fi
    # -----------------------------------------------------------------
    # END TEMPORARY MIGRATION
    # -----------------------------------------------------------------

    return 1
}

# =====================================================================
# ФУНКЦИИ: генерация конфигов из текущих переменных
# =====================================================================

generate_xray_config() {
    mkdir -p /usr/local/etc/xray
    cat > "$XRAY_CONFIG" << XEOF
{
  "log": {
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "vless-reality-in",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "${UUID}",
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "dest": "${REALITY_DEST}:443",
          "serverNames": ["${REALITY_DEST}"],
          "privateKey": "${REALITY_PRIVATE_KEY}",
          "shortIds": ["${SHORT_ID}"]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls", "quic"]
      }
    }
  ],
  "outbounds": [
    {
      "tag": "wg-exit",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP"
      },
      "streamSettings": {
        "sockopt": {
          "interface": "wg0"
        }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom"
    }
  ],
  "dns": {
    "servers": [
      "${WG_DNS}",
      "8.8.8.8"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "inboundTag": ["vless-reality-in"],
        "outboundTag": "wg-exit"
      }
    ]
  }
}
XEOF
}

generate_wg_config() {
    mkdir -p /etc/wireguard
    cat > /etc/wireguard/wg0.conf << WEOF
[Interface]
PrivateKey = ${WG_PRIVATE}
Address = ${WG_CLIENT_IP}/32
MTU = 1280
Table = off

PostUp = ip route add default dev wg0 table wgexit
PostUp = ip rule add from ${WG_CLIENT_IP} table wgexit priority 100
PostUp = sysctl -w net.ipv4.ip_forward=1

PostDown = ip route del default dev wg0 table wgexit 2>/dev/null || true
PostDown = ip rule del from ${WG_CLIENT_IP} table wgexit 2>/dev/null || true

[Peer]
PublicKey = ${FOREIGN_WG_PUBKEY}
Endpoint = ${FOREIGN_IP}:${FOREIGN_PORT}
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
WEOF
    chmod 600 /etc/wireguard/wg0.conf
}

generate_vless_link() {
    echo "vless://${UUID}@${SERVER_IP}:443?encryption=none&flow=xtls-rprx-vision&security=reality&sni=${REALITY_DEST}&fp=chrome&pbk=${REALITY_PUBLIC_KEY}&sid=${SHORT_ID}&type=tcp#RU-VPS-Reality"
}

generate_credentials_file() {
    local VLESS_LINK
    VLESS_LINK=$(generate_vless_link)

    cat > "$CREDENTIALS_FILE" << CEOF
===============================================================
  ДАННЫЕ ПОДКЛЮЧЕНИЯ — Российский VPS
  Сгенерировано: $(date)
===============================================================

--- Для клиента (sing-box / FoXray / v2rayN / Streisand) ---

VLESS-ссылка:
${VLESS_LINK}

--- Для зарубежного VPS ---

WireGuard Public Key (добавить как Peer):
${WG_PUBLIC}

Команда для зарубежного VPS:
sudo wg set wg0 peer ${WG_PUBLIC} allowed-ips ${WG_CLIENT_IP}/32
sudo wg-quick save wg0

--- Параметры ---

UUID:               ${UUID}
Reality Public Key:  ${REALITY_PUBLIC_KEY}
Reality Private Key: ${REALITY_PRIVATE_KEY}
Short ID:           ${SHORT_ID}
Маскировка:         ${REALITY_DEST}
Server IP:          ${SERVER_IP}
WG Client IP:       ${WG_CLIENT_IP}
WG Private Key:     ${WG_PRIVATE}
WG Public Key:      ${WG_PUBLIC}
Foreign Endpoint:   ${FOREIGN_IP}:${FOREIGN_PORT}

===============================================================
CEOF
    chmod 600 "$CREDENTIALS_FILE"
}

print_result() {
    local VLESS_LINK
    VLESS_LINK=$(generate_vless_link)

    echo ""
    echo -e "${GREEN}VLESS-ссылка для клиента:${NC}"
    echo -e "${YELLOW}${VLESS_LINK}${NC}"
    echo ""
    echo -e "${GREEN}WireGuard Public Key (добавить на зарубежный VPS):${NC}"
    echo -e "${YELLOW}${WG_PUBLIC}${NC}"
    echo ""
    echo -e "${GREEN}Команда для зарубежного VPS:${NC}"
    echo -e "${YELLOW}sudo wg set wg0 peer ${WG_PUBLIC} allowed-ips ${WG_CLIENT_IP}/32${NC}"
    echo -e "${YELLOW}sudo wg-quick save wg0${NC}"
    echo ""
    echo -e "${GREEN}Все данные сохранены в:${NC} ${CREDENTIALS_FILE}"
    echo -e "${GREEN}Параметры (machine-readable):${NC} ${PARAMS_FILE}"
    echo ""
}

# =====================================================================
# ОПРЕДЕЛЕНИЕ РЕЖИМА: УСТАНОВКА ИЛИ РЕКОНФИГУРАЦИЯ
# =====================================================================

MODE="install"
XRAY_BIN=$(command -v xray || true)
SERVER_IP=$(curl -s4 ifconfig.me || curl -s4 api.ipify.org || echo "UNKNOWN")

if [[ -f "$XRAY_CONFIG" ]] && load_params; then
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║          Обнаружена существующая настройка                  ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo -e "  UUID:            ${YELLOW}${UUID:-?}${NC}"
    echo -e "  Reality домен:   ${YELLOW}${REALITY_DEST:-?}${NC}"
    echo -e "  Foreign VPS:     ${YELLOW}${FOREIGN_IP:-?}:${FOREIGN_PORT:-?}${NC}"
    echo ""
    echo -e "${CYAN}Что хотите сделать?${NC}"
    echo "  1) Сменить домен маскировки (SNI)"
    echo "  2) Сгенерировать новый UUID"
    echo "  3) Сгенерировать новые Reality ключи"
    echo "  4) Изменить WireGuard (IP/ключи зарубежного VPS)"
    echo "  5) Полная переустановка (все ключи заново)"
    echo "  6) Выход"
    echo ""
    read -rp "Выбор [6]: " CHOICE
    CHOICE=${CHOICE:-6}

    case "$CHOICE" in
        1) MODE="change_sni" ;;
        2) MODE="change_uuid" ;;
        3) MODE="change_reality_keys" ;;
        4) MODE="change_wg" ;;
        5) MODE="install" ;;
        6) log "Выход."; exit 0 ;;
        *) err "Неизвестный выбор: $CHOICE" ;;
    esac
fi

# =====================================================================
# РЕКОНФИГУРАЦИЯ
# =====================================================================

if [[ "$MODE" == "change_sni" ]]; then
    log "Смена домена маскировки Reality"
    echo -e "${YELLOW}Совет: запустите ./find-reality-domain.sh чтобы найти домен в вашем AS${NC}"
    read -rp "Новый домен [${REALITY_DEST}]: " NEW_DEST
    REALITY_DEST=${NEW_DEST:-$REALITY_DEST}

    save_params
    generate_xray_config

    systemctl restart xray
    sleep 2
    systemctl is-active --quiet xray || err "XRay не стартовал! Проверьте: journalctl -u xray -n 20"
    log "XRay перезапущен с доменом: $REALITY_DEST"
fi

if [[ "$MODE" == "change_uuid" ]]; then
    log "Генерация нового UUID"
    [[ -z "$XRAY_BIN" ]] && err "XRay не найден"
    UUID=$($XRAY_BIN uuid)
    log "Новый UUID: $UUID"

    save_params
    generate_xray_config

    systemctl restart xray
    sleep 2
    systemctl is-active --quiet xray || err "XRay не стартовал! Проверьте: journalctl -u xray -n 20"
    log "XRay перезапущен с новым UUID"
fi

if [[ "$MODE" == "change_reality_keys" ]]; then
    log "Генерация новых Reality ключей"
    [[ -z "$XRAY_BIN" ]] && err "XRay не найден"

    REALITY_OUTPUT=$($XRAY_BIN x25519)
    REALITY_PRIVATE_KEY=$(parse_x25519_private "$REALITY_OUTPUT")
    REALITY_PUBLIC_KEY=$(parse_x25519_public "$REALITY_OUTPUT")
    SHORT_ID=$(openssl rand -hex 4)

    log "Новый Reality Public Key: $REALITY_PUBLIC_KEY"
    log "Новый Short ID: $SHORT_ID"

    save_params
    generate_xray_config

    systemctl restart xray
    sleep 2
    systemctl is-active --quiet xray || err "XRay не стартовал! Проверьте: journalctl -u xray -n 20"
    log "XRay перезапущен с новыми Reality ключами"
fi

if [[ "$MODE" == "change_wg" ]]; then
    log "Изменение WireGuard"

    echo -e "${CYAN}=== Новые данные зарубежного VPS ===${NC}"
    read -rp "IP зарубежного VPS [${FOREIGN_IP}]: " NEW_IP
    FOREIGN_IP=${NEW_IP:-$FOREIGN_IP}
    read -rp "Порт WireGuard [${FOREIGN_PORT}]: " NEW_PORT
    FOREIGN_PORT=${NEW_PORT:-$FOREIGN_PORT}
    read -rp "Public Key WireGuard зарубежного VPS: " NEW_PUBKEY
    [[ -z "$NEW_PUBKEY" ]] && err "Public Key не может быть пустым"
    FOREIGN_WG_PUBKEY="$NEW_PUBKEY"
    read -rp "IP в WG-сети [${WG_CLIENT_IP}]: " NEW_WG_IP
    WG_CLIENT_IP=${NEW_WG_IP:-$WG_CLIENT_IP}

    echo ""
    read -rp "Сгенерировать новые WG ключи? [y/N]: " REGEN_WG
    if [[ "$REGEN_WG" =~ ^[Yy] ]]; then
        WG_PRIVATE=$(wg genkey)
        WG_PUBLIC=$(echo "$WG_PRIVATE" | wg pubkey)
        log "Новый WG Public Key: $WG_PUBLIC"
    fi

    # Останавливаем WG
    systemctl stop wg-quick@wg0 2>/dev/null || true
    ip link delete wg0 2>/dev/null || true

    save_params
    generate_wg_config

    wg-quick up wg0
    sleep 2
    ip link show wg0 &>/dev/null || err "Не удалось поднять wg0"
    log "WireGuard перезапущен"

    if [[ "$REGEN_WG" =~ ^[Yy] ]]; then
        echo ""
        warn "WG ключи изменились! Обновите peer на зарубежном VPS:"
        echo -e "  ${YELLOW}sudo wg set wg0 peer ${WG_PUBLIC} allowed-ips ${WG_CLIENT_IP}/32${NC}"
        echo -e "  ${YELLOW}sudo wg-quick save wg0${NC}"
    fi
fi

# --- Завершение реконфигурации ---
if [[ "$MODE" != "install" ]]; then
    generate_credentials_file

    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║                 РЕКОНФИГУРАЦИЯ ЗАВЕРШЕНА                    ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"

    print_result

    warn "Обновите VLESS-ссылку на всех клиентах!"
    echo -e "  Скопируйте .vpn-params на клиент и перезапустите клиентский скрипт:"
    echo -e "  ${YELLOW}scp root@${SERVER_IP}:${PARAMS_FILE} /tmp/ && sudo ./setup-desktop.sh --from /tmp/.vpn-params${NC}"
    echo ""
    exit 0
fi

# =====================================================================
# ПОЛНАЯ УСТАНОВКА (первый запуск или переустановка)
# =====================================================================

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║       Установка XRay VLESS+Reality (Российский VPS)        ║"
echo "║                                                            ║"
echo "║  Клиент → [VLESS/Reality:443] → [sys WG] → Foreign VPS    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# --- Сбор данных ---
echo -e "${CYAN}=== Данные зарубежного VPS ===${NC}"
echo ""

read -rp "IP зарубежного VPS: " FOREIGN_IP
[[ -z "$FOREIGN_IP" ]] && err "IP не может быть пустым"

read -rp "Порт WireGuard [51820]: " FOREIGN_PORT
FOREIGN_PORT=${FOREIGN_PORT:-51820}

read -rp "Public Key WireGuard зарубежного VPS: " FOREIGN_WG_PUBKEY
[[ -z "$FOREIGN_WG_PUBKEY" ]] && err "Public Key не может быть пустым"

read -rp "Ваш IP в WG-сети [10.0.0.2]: " WG_CLIENT_IP
WG_CLIENT_IP=${WG_CLIENT_IP:-10.0.0.2}

echo -e "${YELLOW}Совет: запустите ./find-reality-domain.sh чтобы найти домен в вашем AS${NC}"
read -rp "Сайт для маскировки Reality [www.google.com]: " REALITY_DEST
REALITY_DEST=${REALITY_DEST:-www.google.com}

# =====================================================================
# 1. УСТАНОВКА ПАКЕТОВ
# =====================================================================
log "Устанавливаю пакеты..."

if ! command -v xray &>/dev/null; then
    log "Устанавливаю XRay..."
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
else
    log "XRay уже установлен: $(xray version 2>/dev/null | head -1)"
fi

if ! command -v wg &>/dev/null; then
    log "Устанавливаю wireguard-tools..."
    if [[ -f /etc/debian_version ]]; then
        apt update -qq && apt install -y -qq wireguard wireguard-tools
    elif [[ -f /etc/redhat-release ]]; then
        yum install -y epel-release && yum install -y wireguard-tools
    else
        apt update -qq && apt install -y -qq wireguard wireguard-tools
    fi
else
    log "wireguard-tools уже установлены"
fi

XRAY_BIN=$(command -v xray)

# =====================================================================
# 2. ГЕНЕРАЦИЯ КЛЮЧЕЙ
# =====================================================================
log "Генерирую ключи..."

UUID=$($XRAY_BIN uuid)
log "UUID: $UUID"

REALITY_OUTPUT=$($XRAY_BIN x25519)
REALITY_PRIVATE_KEY=$(parse_x25519_private "$REALITY_OUTPUT")
REALITY_PUBLIC_KEY=$(parse_x25519_public "$REALITY_OUTPUT")
[[ -z "$REALITY_PRIVATE_KEY" ]] && err "Не удалось получить Reality Private Key.\nВывод: $REALITY_OUTPUT"
[[ -z "$REALITY_PUBLIC_KEY" ]] && err "Не удалось получить Reality Public Key.\nВывод: $REALITY_OUTPUT"
log "Reality Private Key: $REALITY_PRIVATE_KEY"
log "Reality Public Key:  $REALITY_PUBLIC_KEY"

SHORT_ID=$(openssl rand -hex 4)
log "Short ID: $SHORT_ID"

WG_PRIVATE=$(wg genkey)
WG_PUBLIC=$(echo "$WG_PRIVATE" | wg pubkey)
[[ ${#WG_PUBLIC} -ne 44 ]] && warn "WG Public Key нестандартная длина: ${#WG_PUBLIC}"
log "WG Private Key: ${WG_PRIVATE:0:10}..."
log "WG Public Key:  $WG_PUBLIC"

SERVER_IP=$(curl -s4 ifconfig.me || curl -s4 api.ipify.org || echo "UNKNOWN")
log "IP этого сервера: $SERVER_IP"

# Сохраняем параметры
save_params
log "Параметры сохранены в $PARAMS_FILE"

# =====================================================================
# 3. СИСТЕМНЫЙ WIREGUARD С POLICY ROUTING
# =====================================================================
log "Настраиваю системный WireGuard..."

systemctl stop xray 2>/dev/null || true
systemctl stop wg-quick@wg0 2>/dev/null || true
ip link delete wg0 2>/dev/null || true
ip rule del from "$WG_CLIENT_IP" table wgexit 2>/dev/null || true
ip route del default table wgexit 2>/dev/null || true

if ! grep -q "^100 wgexit" /etc/iproute2/rt_tables 2>/dev/null; then
    echo "100 wgexit" >> /etc/iproute2/rt_tables
fi

generate_wg_config

wg-quick up wg0
systemctl enable wg-quick@wg0

sleep 2

if ip link show wg0 &>/dev/null; then
    log "WireGuard wg0 поднят"
else
    err "Не удалось поднять wg0"
fi

log "Проверяю связь через WireGuard..."
if ping -c 2 -W 3 -I wg0 "$WG_DNS" &>/dev/null; then
    log "Ping через WG проходит — туннель работает!"
else
    warn "Ping через WG не прошёл — проверьте что Peer добавлен на зарубежном VPS"
fi

# =====================================================================
# 4. КОНФИГ XRAY
# =====================================================================
log "Создаю конфиг XRay..."

generate_xray_config

log "Проверяю конфиг XRay..."
if xray run -test -config "$XRAY_CONFIG" 2>&1 | grep -q "Configuration OK"; then
    log "Конфиг валидный"
else
    warn "Результат проверки:"
    xray run -test -config "$XRAY_CONFIG"
fi

# =====================================================================
# 5. ФАЙРВОЛ И ЗАПУСК
# =====================================================================
log "Настраиваю файрвол..."
if command -v ufw &>/dev/null; then
    ufw allow 443/tcp 2>/dev/null || true
    log "UFW: порт 443/tcp открыт"
elif command -v firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --add-port=443/tcp 2>/dev/null || true
    firewall-cmd --reload 2>/dev/null || true
    log "firewalld: порт 443/tcp открыт"
fi

log "Запускаю XRay..."
systemctl daemon-reload
systemctl enable xray
systemctl restart xray

sleep 3

if systemctl is-active --quiet xray; then
    log "XRay запущен и работает!"
else
    warn "XRay не стартовал. Логи:"
    journalctl -u xray -n 15 --no-pager
    echo ""
    err "XRay не запустился."
fi

# =====================================================================
# 6. СОХРАНЕНИЕ ДАННЫХ ПОДКЛЮЧЕНИЯ
# =====================================================================

generate_credentials_file
log "Данные подключения сохранены в ${CREDENTIALS_FILE}"

# =====================================================================
# 7. ВЫВОД РЕЗУЛЬТАТОВ
# =====================================================================

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                    УСТАНОВКА ЗАВЕРШЕНА                      ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"

print_result

echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║                  НАСТРОЙКА КЛИЕНТОВ                         ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}  Desktop (Mac / Ubuntu / Debian):${NC}"
echo -e "    ${YELLOW}scp root@${SERVER_IP}:${PARAMS_FILE} /tmp/${NC}"
echo -e "    ${YELLOW}sudo ./clients/setup-desktop.sh --from /tmp/.vpn-params${NC}"
echo ""
echo -e "${CYAN}  Keenetic:${NC}"
echo -e "    ${YELLOW}scp root@${SERVER_IP}:${PARAMS_FILE} root@<router-ip>:/opt/${NC}"
echo -e "    ${YELLOW}ssh root@<router-ip> '/opt/setup-keenetic.sh --from /opt/.vpn-params'${NC}"
echo ""
echo -e "${CYAN}  OpenWrt:${NC}"
echo -e "    ${YELLOW}scp root@${SERVER_IP}:${PARAMS_FILE} root@<router-ip>:/tmp/${NC}"
echo -e "    ${YELLOW}ssh root@<router-ip> '/tmp/setup-openwrt.sh --from /tmp/.vpn-params'${NC}"
echo ""
echo -e "${CYAN}  iOS:${NC} FoXray / Streisand — импорт VLESS-ссылки"
echo -e "${CYAN}  Android:${NC} v2rayNG — импорт VLESS-ссылки"
echo ""
echo -e "${CYAN}  Проверка (на клиенте):${NC}"
echo -e "    ${YELLOW}curl -4 ifconfig.me${NC}"
echo ""
echo -e "  Домены .ru / .рф / .su идут напрямую без VPN."
echo ""
